name: Deploy website
on:
  push:
    branches:
      - main
      - develop

jobs:
  DevDeploy:
    name: Build and deploy for dev
    if: github.event.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://portfolio-dev-33a95.web.app
    steps:
      - uses: actions/checkout@v3
      - run: 'npm i && npm run build:dev'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_DEV_33A95 }}'
          channelId: live
          projectId: portfolio-dev-33a95

  ProdBuild:
      name: Build for production
      if: github.event.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
  
        - name: Setup Node
          uses: actions/setup-node@v3
  
        - name: Install dependencies
          run: npm ci
  
        - name: Build project
          run: npm run build:prod

  DeployProd:
    name: Deploy to Prod 
    if: github.event.ref == 'refs/heads/main'
    needs: ProdBuild
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://alex-dishen.github.io/portfolio/
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

